# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='kwargs',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='method',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
